# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
