# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20160311_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
