# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160309_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_main', to='posts.Post', verbose_name='Main'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_parent', to='posts.Post', verbose_name='Parent'),
        ),
    ]
