# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20160317_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_parent', to='posts.Comment', verbose_name='Parent'),
        ),
    ]
